### ISSUE TITLE
[macOS] building from code scripts and manual build not functioning

### ISSUE THREAD

**Issue by KineticLabs25** [Spagett1/PineFlash#27] opened 2023-04-07 00:58 UTC
Build Option 1:
After cloning and running generic_linux_install.sh, the terminal returns:

```
generic_linux_install.sh: line 20: syntax error near unexpected token 'else'
generic_linux_install.sh: line 20: 'else'
```

Build Option 2:
Trying to build manually, the command `sudo mv ./tools/blisp/blisp /usr/bin/` needs to be changed to `sudo mv ./tools/blisp/blisp /usr/local/bin/` in macOS.

Once blisp has been built, running 'cargo build --release' compiles a while then returns:

```
error[E0425]: cannot find value `target_dir` in this scope
   --> src/main.rs:239:62
    |
239 | ...sor::new(data), &target_dir, false).unwrap();
    |                     ^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `pineflash` due to previous error
```

**Comment by Spagett1** [comment] 2023-04-07 01:04
The build script has been updated, would you mind giving it another crack and letting me know if the cargo error still occurs? Cheers

**Comment by Djhg2000** [comment] 2023-04-11 01:02
I can confirm the same compilation bug also occurs on Debian Sid.

**Comment by Djhg2000** [comment] 2023-04-11 22:40
I'd rather still compile `blisp` in the process, but the cargo build work fine now.

**Comment by Spagett1** [comment] 2023-04-11 22:44
The reason ive switched the instructions and script to downloading blisp is because the current blisp master  branch is broken for macos and its easier for people not used to compiling to just download it. Feel free to compile it though it shouldnt have any issues doing that. Glad to hear the cargo problems fixed on debian.

Once i can get kineticlabs to test it on macos ill close this issue.

**Comment by Djhg2000** [comment] 2023-04-11 22:52
Yeah I put together a quick script (or rather, three lazy one-liners in a file) to build everything from source. It has very rudimentary error handling but it works well enough for me at the moment:

```
rm -rf PineFlash; git clone https://github.com/Spagett1/PineFlash/ && cd PineFlash

rm blisp && git clone --recursive https://github.com/pine64/blisp.git && cd blisp && git submodule update --init --recursive && mkdir build && cd build && cmake -DBLISP_BUILD_CLI=ON .. && cmake --build . && sudo cp -v ./tools/blisp/blisp /usr/local/bin/ && cd ../..

cargo build --release && sudo cp -v ./target/release/pineflash /usr/local/bin/
```

**Comment by Spagett1** [comment] 2023-04-11 22:55
Yeah that seems pretty similar to the generic_unix_install.sh script ive got in the repo (aside from it downloading blisp binaries depending on os and compiling it if on arm not x86_64)

**Comment by KineticLabs25** [comment] 2023-04-11 23:35
Script works! I was able to build Pineflash and successfully flash the firmware on my V2.

I did however get a message at the end of building:

```
replace blisp? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: blisp                   
Password:
cp: /usr/bin/pineflash: Operation not permitted
```

Didn't seem to impact functionality, though I've built blisp myself prior to trying out Pineflash. Could this have something to do with not using /usr/local/bin/ instead of /usr/bin/?

**Comment by Spagett1** [comment] 2023-04-12 05:51
That message is just because there is a folder named `blisp` and its trying to extract to `blisp` this wont be an issue for anyone who downloads the latest source code since it doesnt include the blisp folder. Thanks!

**Closed by Spagett1** 2023-04-12 05:51 UTC
Labels: bug, Testing needed
